export const SESSION_RECEIVED = "SESSION_RECEIVED";
export const USER_LOGOUT = "USER_LOGOUT";
export const MAKE_SENDSAY_REQUEST = "MAKE_SENDSAY_REQUEST";
export const RECEIVE_SENDSAY_RESPONSE = "RECEIVE_SENDSAY_RESPONSE";
export const REMOVE_REQUEST_FROM_HISTORY = "REMOVE_REQUEST_FROM_HISTORY";
export const CLEAR_REQUEST_HISTORY = "CLEAR_REQUEST_HISTORY";
export const SET_CONSOLE_RATIO = "SET_CONSOLE_RATIO";
export const SET_CONSOLE_INPUT_VALUE = "SET_CONSOLE_INPUT_VALUE";
